name: Publish python app to docker
on:
  push:
    branches: [main]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_API_KEY }} | docker login -u "hasanaburayyan" --password-stdin

      - name: Build the docker image
        run: docker build -t hasanaburayyan/simple-python-app:latest .

      - name: Push Image artifact to the hub
        run: docker push hasanaburayyan/simple-python-app:latest
      
